### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by mistermantas** [12px/eddited#3]
Most open source projects have a license, so that’d be nice for this thing.

This might be useful: https://choosealicense.com

**Comment by mistermantas** [comment]
@12px yo, you up?

**Comment by 12px** [comment]
I swear, I am not getting any notifications about these issues. I need to edit my github settings, surely. It says I'm getting notifications but I didn't get an email or anything about this. Hi, what's up?

**Comment by mistermantas** [comment]
Amazing, you actually fixed an issue that is — *counts* — 5 months old. Congrats! I thought you just kind of forgot this project existed (which I wouldn’t blame you for). I’m guessing the other one I suggested (#2) you didn’t think was neccesary?

**Comment by 12px** [comment]
I didn't forget it existed, I just lived in the command line and forgot
GitHub existed. I only remembered when someone posted a link to an issue in
the subreddit. And it might happen, but there are no plans at this moment
for a fixed sidebar. There would need to be a lot of small tweaks to
support it, otherwise it'd be an easy toggle.
